# Generated by Django 4.2.7 on 2023-12-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_post_image_post_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-updated', '-publish')},
        ),
    ]
